// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BIM.Booking.Domain.Models;

public partial class Admin
{
    [Key]
    public int AdminId { get; set; }

    [Column("Identity_UserId")]
    public int IdentityUserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(20)]
    public string Phone { get; set; }

    public string Image { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [ForeignKey("IdentityUserId")]
    [InverseProperty("Admin")]
    public virtual IdentityUser IdentityUser { get; set; }
}