// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BIM.Booking.Domain.Models;

public partial class Appointments
{
    [Key]
    public int AppointmentId { get; set; }

    [Column(TypeName = "date")]
    public DateTime AppointmentDate { get; set; }

    public TimeSpan AppointmentTime { get; set; }

    [Required]
    [StringLength(50)]
    public string AppointmentStatus { get; set; }

    public int PeopleLimit { get; set; }

    public int DoctorId { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("Appointments")]
    public virtual Doctors Doctor { get; set; }
}