// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BIM.Booking.Domain.Models;

public partial class Bookings
{
    [Key]
    public int BookingId { get; set; }

    public int HospitalId { get; set; }

    public int DoctorId { get; set; }

    public int PatientId { get; set; }

    public int ServiceId { get; set; }

    public int PaymentId { get; set; }

    [Required]
    [StringLength(100)]
    public string TicketNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifyDate { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("Bookings")]
    public virtual Doctors Doctor { get; set; }

    [ForeignKey("HospitalId")]
    [InverseProperty("Bookings")]
    public virtual Hospital Hospital { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("Bookings")]
    public virtual Patients Patient { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("Bookings")]
    public virtual Payments Payment { get; set; }

    [ForeignKey("ServiceId")]
    [InverseProperty("Bookings")]
    public virtual DoctorService Service { get; set; }
}