// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BIM.Booking.Domain.Models;

[Table("Doctor_Service")]
public partial class DoctorService
{
    [Key]
    public int ServiceId { get; set; }

    [Required]
    [StringLength(50)]
    public string ServiceName { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [InverseProperty("Service")]
    public virtual ICollection<Bookings> Bookings { get; set; } = new List<Bookings>();

    [InverseProperty("Service")]
    public virtual ICollection<Doctors> Doctors { get; set; } = new List<Doctors>();
}