// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BIM.Booking.Domain.Models;

public partial class Doctors
{
    [Key]
    public int DoctorId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(100)]
    public string Qualification { get; set; }

    public int ServiceId { get; set; }

    public int HospitalId { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [InverseProperty("Doctor")]
    public virtual ICollection<Appointments> Appointments { get; set; } = new List<Appointments>();

    [InverseProperty("Doctor")]
    public virtual ICollection<Bookings> Bookings { get; set; } = new List<Bookings>();

    [ForeignKey("HospitalId")]
    [InverseProperty("Doctors")]
    public virtual Hospital Hospital { get; set; }

    [ForeignKey("ServiceId")]
    [InverseProperty("Doctors")]
    public virtual DoctorService Service { get; set; }
}