// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BIM.Booking.Domain.Models;

public partial class HospitalServices
{
   [ Key ]
    public int HospitalServiceId { get; set; }

    [Required]
    [StringLength(50)]
    public string ServiceName { get; set; }

    [Required]
    [StringLength(1000)]
    public string Description { get; set; }

  //  [Column("Hospital_Id")]
    public int HospitalId { get; set; }

    [Required]
    public bool IsActive { get; set; }

    [ForeignKey("HospitalId")]
    [InverseProperty("HospitalServices")]
    public virtual Hospital Hospital { get; set; }
}