// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BIM.Booking.Domain.Models;

public partial class Patients
{
    [Key]
    public int PatientId { get; set; }

    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(100)]
    public string DateOfBirth { get; set; }

    [Required]
    [StringLength(50)]
    public string Gender { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    [Required]
    [StringLength(100)]
    public string Address { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [InverseProperty("Patient")]
    public virtual ICollection<Bookings> Bookings { get; set; } = new List<Bookings>();

    [ForeignKey("UserId")]
    [InverseProperty("Patients")]
    public virtual IdentityUser User { get; set; }
}