// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BIM.Booking.Domain.Models;

public partial class Payments
{
    [Key]
    public int PaymentId { get; set; }

    [Required]
    [StringLength(50)]
    public string PaymentName { get; set; }

    [Required]
    public bool? IsActive { get; set; }

    [InverseProperty("Payment")]
    public virtual ICollection<Bookings> Bookings { get; set; } = new List<Bookings>();
}